Integrated the webmake-generated docs with doxygen ones. This one using html2wmk perl script.
Minor documentation updates and fixes.


git-svn-id: https://svn.code.sf.net/p/dgd/svn/trunk@35 e1490235-051b-40e1-b061-1d7fae7c56ee

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3022,7 +3022,7 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-ac_config_files="$ac_config_files Makefile doc/Makefile doc/dgd.wmk doc/doxygen/dgd.doxy getopt/Makefile regex/Makefile dgd/Makefile dgd/src/dgConfig.h dgd/src/dgDebugOpt.gge test/Makefile"
+ac_config_files="$ac_config_files Makefile doc/Makefile doc/html/dgd.wmk doc/doxygen/dgd.doxy getopt/Makefile regex/Makefile dgd/Makefile dgd/src/dgConfig.h dgd/src/dgDebugOpt.gge test/Makefile util/bin/mkdis util/bin/copytree"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3356,7 +3356,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  "doc/dgd.wmk" ) CONFIG_FILES="$CONFIG_FILES doc/dgd.wmk" ;;
+  "doc/html/dgd.wmk" ) CONFIG_FILES="$CONFIG_FILES doc/html/dgd.wmk" ;;
   "doc/doxygen/dgd.doxy" ) CONFIG_FILES="$CONFIG_FILES doc/doxygen/dgd.doxy" ;;
   "getopt/Makefile" ) CONFIG_FILES="$CONFIG_FILES getopt/Makefile" ;;
   "regex/Makefile" ) CONFIG_FILES="$CONFIG_FILES regex/Makefile" ;;
@@ -3364,7 +3364,9 @@ do
   "dgd/src/dgConfig.h" ) CONFIG_FILES="$CONFIG_FILES dgd/src/dgConfig.h" ;;
   "dgd/src/dgDebugOpt.gge" ) CONFIG_FILES="$CONFIG_FILES dgd/src/dgDebugOpt.gge" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
-  *) { { echo "$as_me:3367: error: invalid argument: $ac_config_target" >&5
+  "util/bin/mkdis" ) CONFIG_FILES="$CONFIG_FILES util/bin/mkdis" ;;
+  "util/bin/copytree" ) CONFIG_FILES="$CONFIG_FILES util/bin/copytree" ;;
+  *) { { echo "$as_me:3369: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3606,7 +3608,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3609: creating $ac_file" >&5
+    { echo "$as_me:3611: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3624,7 +3626,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3627: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3629: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3637,7 +3639,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3640: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3642: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
